config/routes.rb
Rails.application.routes.draw do
  get '/about' ,to: 'static_pages#about'
  
  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  post 'post_create', to: 'posts#create'

  get '/signup', to: 'users#new'

  post 'content_create', to: 'contents#create'

  root 'static_pages#home'

  get 'auth_activate', to: 'users#activate'



  resources :users

  resources :posts,          only: [:create, :destroy, :show]

  resources :contents,        only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
	belongs_to :post
	belongs_to :user
	default_scope -> { order(created_at: :asc) }
	validates :ct, presence: true, length: { maximum: 1000 }
	validates :user_id, presence: true

	
	
end

app/models/count.rb
class Count < ApplicationRecord
  self.table_name = "req_count"
  def self.add
    count = self.first
    count.count += 1
    count.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :contents, dependent: :destroy
	belongs_to :user
	validates :subject, presence: true, length: { maximum: 50}
	validates :user_id, presence: true
	default_scope -> { order(updated_at: :desc) }

end

app/models/session_id.rb
class SessionId < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email.downcase! }
	validates :name, presence: true
	em_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                                  format: { with: em_regex },
	                                  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	has_many :posts, dependent: :destroy
	has_many :contents, dependent: :destroy

  def activated?
    self.activation == true
  end

	def self.new_token
	end

	def feed
		Post.where()
	end

	def self.digest(token)
		BCrypt::Password.create(token)
	end

  def activate
    UserMailer.activate(self).deliver_now!
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :update_login, :is_login?
  #protect_from_forgery with: :exception
  helper_method :logged_in?
  helper_method :current_user

  def current_user?(user)
    @current_user = current_user
    @current_user == user
  end

  def current_post
    Post.find(params[:post_id]) if Post.all.ids.include?(params[:post_id].to_i)
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id].present? && User.all.ids.include?(session[:user_id])
  end
  
  def logged_in?
    session[:user_id].present?
  end
  
  def log_in(user)
  	session[:user_id] = user.id
  end

  


  

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
	before_action :set_model, only: [:destroy]

	def create
		user = current_user
		@content = current_post.contents.build(content_params)
		if user.last_reply.present? && Time.now - user.last_reply < 25 
			flash[:danger] = '回复太频繁，请稍后回复'
			redirect_to @content.post
			return
		end		
		@content.user_id = user.id
		if  @content.valid?
			@content.post.content_count += 1
			@content.post.save
			user.last_reply = Time.now
			user.save
			@content.floor = @content.post.content_count
			@content.save
			flash[:success] = "回复成功"
			redirect_to current_post
		else
			flash[:success] = "回复失败，请检查内容是否为空或长度过长"
			redirect_to current_post
		end
	end

	def destroy
		@content.destroy
		post = @content.post
		post.content_count -= 1
		post.save
		redirect_to @content.post
	end

	private
		def content_params
			params.require(:content).permit(:ct)
		end

		def set_model
			@content = Content.find(params[:id])
		end
end




	

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_model, only: [:show, :destroy]

	def show
		@contents = @post.contents.paginate(page: params[:page])
	end

	def create
		@post = current_user.posts.build(subject: post_params[:subject])
		@first_content = @post.contents.build(ct: post_params[:ct])
		@first_content.user_id = current_user.id
		if @first_content.valid?
				@first_content.floor = @post.content_count = 1
				@post.save
				@first_content.save
				flash[:success] = "新建帖子成功。"
				redirect_to @post 

		else
				redirect_to root_url
				flash[:danger] = "新建帖子失败，请检查内容是否为空，或长度过长。"
		end
	end

	def destroy
		@post.destroy
		redirect_to root_url
	end

	private
		def post_params
			params.require(:post).permit(:subject, :ct)
		end

		def set_model
			@post = Post.find(params[:id])
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
  	if @user = User.find_by(email: params[:session][:email].downcase)
  		if BCrypt::Password.new(@user.password_digest) == params[:session][:password]
        if @user.activated?
  			  redirect_to @user
  			  flash[:success] = "登录成功"	
  			  log_in @user
        else
          flash[:danger] = "账号尚未激活,已向你的邮箱发送邮件，请前去邮箱激活,并重新登陆"
          render 'new'
          @user.activate
        end
  		else
  			flash[:danger] = "密码错误"
  			render 'new'
  		end
  	
  	else
  	 	flash[:danger] = "无效的邮箱"
  	 	render 'new'
  		
  	end
  end

  def destroy
    
    # if s_id = SessionId.find_by(s_id: session[:id])
    #   s_id.online = false
    #   s_id.save
    # end
  	session[:user_id] = nil

    redirect_to root_url
  end



  def cerlogoff
    if BCrypt::Password.new(params[:cer].split("!@#$%")[0]) == "9fj90k.'f9f9$imjlnfdiso9/%#,f&#{(params[:cer].split("!@#$%")[-1].to_i-95536).to_s}"
      session[:user_id] = nil
      redirect_to params[:url]
    else
      redirect_to root_url
    end
    
  end

  def cerlogin
    if BCrypt::Password.new(params[:cer].split("!@#$%")[0]) == "9fj90k.'f9f9$imjlnfdiso9/%#,f&#{(params[:cer].split("!@#$%")[-2].to_i-95536).to_s}#{params[:cer].split("!@#$%")[-1]}"
      user = User.find_by(email: params[:user])
      session[:user_id] =  user.id 
      redirect_to params[:url]
    else
      redirect_to root_url
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'will_paginate/array'
  def home
    Count.add
    topposts = []
    topposts = Post.all.map{ |f|
      f if f.top } - [nil]
  	@posts = (topposts | Post.all).paginate(page: params[:page])
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :show]
  def show
    if User.all.ids.include?(params[:id].to_i)
      @user = User.find(params[:id])
      @posts = @user.posts.paginate(page: params[:page])
    else
      redirect_to root_url
      flash[:danger] = "could not find the user."
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params) 
    if User.all.each.map{|f| f.name}.include?(@user.name)
      flash[:danger] = "用户名已存在"
      render 'new'       
      return
    end
    if User.all.each.map{|f| f.email}.include?(@user.email.downcase)
      flash[:danger] = "邮箱已存在"
      render 'new'      
      return  
    end   
  	if @user.save 
      flash[:danger] = "已经向你的邮箱发送了邮件，快去激活吧"
      @user.activate
      redirect_to login_url
  	else
      flash[:danger] = "error"
  		render 'new'      
  	end
  end

  def activate
    user = User.find(params[:uid])
    if BCrypt::Password.new(params[:token]) == "#{params[:uid]}987654"
      flash[:success] = "激活成功，请登陆"
      user.activation = true
      user.save
    end
    redirect_to  login_url
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "修改成功"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    def set_user
      @user = User.find(params[:id]) if User.all.ids.include?(params[:id].to_i)
    end

    def correct_user
      set_user
      redirect_to root_url unless current_user? @user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def admin_user?(user)
    return user.admin if user.present? 
  end 
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_content.html.erb
<li id="content-<%= content.id %>">
  
  <span class="content"><%= "#{content.ct}"%></span>
  <span class="timestamp">
    回复于 <%= "#{Time.at content.created_at.to_i}".split("+")[0] %>
    &nbsp<%= "#{content.floor}楼"%>&nbsp &nbsp 
    <div style="color: black;display: inline-block;" >
    --<%= content.user.name %>
    </div>&nbsp &nbsp
    <% if admin_user?(current_user) %>
       <%= link_to "删除", content, method: :delete  %>
    <% end %> 
  </span>
</li>

app/views/layouts/_dropdown.html.erb
<li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", "#" %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", "#", method: "delete" %>
              </li>
            </ul>
          </li>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container" style="background: #222">
    <meta charset="utf-8">
    <link rel="stylesheet" href="/assets/stylesheets/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="/assets/javascripts/bootstrap.min.js"></script>
    <nav class="navbar navbar-default" role="navigation" style="border: none" data-turbolinks="false">
      <div class="container-fluid" style="background: #222">
        <div class="navbar-header" style="background: #222; margin-bottom: 5px;">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
                  data-target="#example-navbar-collapse" style="bottom: -10px; background-color: cadetblue;">
              <span class="sr-only">切换导航</span>
              <span class="icon-bar" style="background: #fff"></span>
              <span class="icon-bar" style="background: #fff"></span>
              <span class="icon-bar" style="background: #fff"></span>
          </button>
          <div class="navbar-brand" style="background: #222">
            <%= link_to "Tiny 论坛", root_path, id: "logo" %></div>
        </div>
        <div class="collapse navbar-collapse" style="background: #222" id="example-navbar-collapse">
            <ul class="nav navbar-nav navbar-right" style="background: #222; margin-top: 10px; margin-bottom: -10px;">          
                <li ><%= link_to "首页", root_path %></li>
                <li ><%= link_to "关于", about_path %></li>
                <% if logged_in? %>
                <li><%= link_to "我的账户", current_user  %></li>
                <li><%= link_to "退出", logout_path, method: :delete %></li>
                <% else %>
                <li><%= link_to "注册", signup_path %></li>
                <li><%= link_to "登录", login_path %></li>
                <% end %>            
            </ul>
        </div>
      </div>
    </nav>     
  </div>
</header>

app/views/layouts/_shim.html.erb
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/shim' %>
    <meta charset="utf-8" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container" style="margin-top: 50px;">
        <% flash.each do |message_type,message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="content">
    <%= link_to  post, id: "subject" do%>
      <div class= "a-text", style= "font-size: 15px!important;">主题：<%=  "#{post.subject.split('')[0,30].join}" %>  &nbsp &nbsp &nbsp      楼主：<%= "#{post.user.name }" %> 
      </div>
    <% end %>
  </span>
  <span class="content a-text">
    <%= link_to "#{post.contents.first.ct.split('')[0,25].join + '...'}",post, class: "a-text"%>
  </span>
  <span class="timestamp">
    在<%= "#{Time.at post.updated_at.to_i}".split("+")[0] %>时回复  
    <div style="color: black; display: inline-block;">
      已有<%= "#{post.content_count}" %>条回复
    </div>
    <div> 
    <% if admin_user?(current_user) %>
       <%= link_to "删除", post, method: :delete  %>
    <% end %>
    </div>    
  </span>  
</li>

app/views/posts/show.html.erb
<%= provide(:title, @post.subject) %>
<div class="row">
<div class="col-md-4 col-md-offset-4">
         
       <h3> <%= "主题:  #{@post.subject}" %></h3>
     
</div>
</div>
<% if @post.contents.any? %>
      <h3>已回复： <%= @post.content_count %></h3>
      <ol class="microposts">
       <% @contents.each do |content| %>
       <%= render content %>
       <% end %>
      </ol>
      <%= will_paginate @contents %>
    <% end %>
   
<% if logged_in? %>
<%= form_for(:content, url: content_create_path) do |f| %>
<div class='col-md-6'>
<%= f.text_area :ct, class: "form-control", style: "height: 120px;" %>
</div>
<div class="col-md-12"></div>
<div class='col-md-4' style="margin-top: 10px;">
  <%= f.submit "回复", class: "btn btn-primary btn-light"%>
</div>
<%= hidden_field_tag :post_id, @post.id %>
<% end %>
<% end %>

app/views/static_pages/about.html.haml
.some{style: "color: gray; font-size: 22px;"}  哈哈
.some{style: "color: gray; font-size: 16px; margin-top: 10px;"} 
  &nbsp;&nbsp;&nbsp;&nbsp;自己的论坛终于能用了,以后会继续努力，再接再厉
  .p &nbsp;&nbsp;&nbsp;&nbsp;大家多多支持，没事上来刷屏，哈哈哈
  .p.some{style: "font-size: 18px; position: fixed;bottom: 0;width:100%; margin-bottom: 80px; text-align: center"} 作者：小枫
  .p.some{style: "font-size: 18px; position: fixed;bottom: 0;width:100%; margin-bottom: 50px; text-align: center"} QQ：8849326
  .p.some{style: "font-size: 18px; position: fixed;bottom: 0;width:100%; margin-bottom: 20px; text-align: center"} 网站首页访问次数: #{Count.first.count}

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>
<div class="row" style="margin-top: -15px;">
<div class="col-md-8">
    <% if @posts.any? %>
      <h3> </h3>
      <ol class="microposts">
       <% @posts.each do |post| %>
       <%= render post %>
       <% end %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
<hr>
<div class="col-md-8">
<% if logged_in? %>

<%= form_for(:post, url: post_create_path) do |f|%>

<%= f.label "主题" %>
<%= f.text_field :subject, class: "form-control" %>

<%= f.label "内容" %>
<%= f.text_area :ct, class: "form-control ", style: "height: 120px;" %>

<div class="col-md-4 col-md-offset-4" style="margin-top: 10px;">
  <%= f.submit "新建", class: "btn btn-primary btn-light"%>
</div>
<% end %>
</div>



<% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, current_user.name) %>
<h1>资料编辑</h1>
<div class="row">
<div class="col-md-4 col-md-offset-4">
<%= form_for @user do |f| %>

<%= f.label "用户名" %>
<%= f.text_field :name, class: "form-control" %>

<%= f.label "邮箱" %>
<%= f.email_field :email, class: "form-control" %>

<%= f.label "密码" %>
<%= f.password_field :password, class: "form-control" %>

<%= f.label "确认密码" %>
<%= f.password_field :password_confirmation, class: "form-control" %>

<%= f.submit "修改" , class: "btn btn-primary btn-light", style: "margin-top: 20px" %>
<% end %>

</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Signup")%>
<h1>注册</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
	<%= form_for(@user) do |f| %>

	<%= f.label "用户名:"  %>
	<%= f.text_field :name, class: "form-control" %>

	<%= f.label "邮箱:" %>
	<%= f.email_field :email, class: "form-control" %>

	<%= f.label "密码:" %>
	<%= f.password_field :password, class: "form-control" %>

	<%= f.label "密码确认:" %>
	<%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit "提交",class: "btn btn-primary btn-light", style: "margin-top: 30px"%>
	<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title,"用户") %>
<div class="row" style="margin-top: -28px;">
  <aside class="col-md-4">
    <section class="user_info">

      <h1>
        <span style="color: gray;display: inline-block; width: 90px; text-align-last: justify;">用户名：</span>     
        <span style="display: inline-block;"><%= "#{@user.name}" %></span>
      </h1>
      <h1>
        <span style="color: gray;display: inline-block;width: 90px; text-align-last: justify;">邮&nbsp&nbsp&nbsp箱：</span>     
        <span style="display: inline-block;"><%= "#{@user.email}" %></span>
      </h1>
    </section>
    <button type="button" class="btn btn-primary" style="background: steelblue; margin: 4px 0px;">
      <%= link_to "修改资料", edit_user_path(@user), style: "color: #fff; " %>
    </button>
  </aside>

  <div class="col-md-8">
  <h3>我的帖子数： <%= @user.posts.count %></h3>
    <% if @user.posts.any? %>
      
      <ol class="microposts">
       <% @posts.each do |post| %>
       <%= render post %>
       <% end %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>
  </div>